### ISSUE TITLE
Help wanted !

### ISSUE THREAD

**Issue by chatmurai** [plapointe6/CustomHADevicesCollection#1]
Hi Patrick, nice lib but no matter I try my device never shows up in HA entities list.
I am able to execute commands from CLI like `~ mosquitto_pub -t ha/light/desk_light/cmd -m "OFF"` or  using the test UI in HA MQTT settings, but no entity is ever created in HA.

Here is my code on the esp side :
```
EspMQTTClient client(
    "MyWifiSSID",
    "MyWifiPassword",
    "192.168.10.60",
    "mqtt_user",
    "mqtt_password",
    "desk_light",
    1883
);

HAMqttDevice light("desk_light", HAMqttDevice::LIGHT);
```
And the one in HA configuration.yaml :
```
mqtt:
  broker: 127.0.0.1
  username: 'mqtt_user'
  password: '*************'
  discovery_prefix: 'ha'
  discovery: true
  birth_message:
    topic: 'ha/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'ha/status'
    payload: 'offline'
    retain: true
```
The serial debug log in PlatformIO :
```
WiFi: Connected (4.858000s), ip : 192.168.10.64 
WEB: Updater ready, open http://desk_light.local in your browser and login with username '********' and password '********'.
MQTT: Connecting to broker "192.168.10.60" with client name "desk_light" ... (5.364000s) - ok. (5.379000s) 
MQTT: Subscribed to [ha/light/desk_light/cmd]
MQTT: Subscribed to [ha/status]
MQTT >> [ha/light/desk_light/cmd] ON
MQTT << [ha/light/desk_light/state] ON
MQTT >> [ha/light/desk_light/cmd] OFF
MQTT << [ha/light/desk_light/state] OFF
```

HA is installed on a RBPi 3 and I use Mosquitto broker integration.

I am pulling my hair off on this one, and would appreciate your help ! Thanks a lot !
